In [1]:
import numpy as np
import pandas as pd

In [2]:
autos = pd.read_csv("autos.csv", encoding="Latin-1")

In [3]:
autos

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [4]:
autos.info()
autos.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
dateCrawled            50000 non-null object
name                   50000 non-null object
seller                 50000 non-null object
offerType              50000 non-null object
price                  50000 non-null object
abtest                 50000 non-null object
vehicleType            44905 non-null object
yearOfRegistration     50000 non-null int64
gearbox                47320 non-null object
powerPS                50000 non-null int64
model                  47242 non-null object
odometer               50000 non-null object
monthOfRegistration    50000 non-null int64
fuelType               45518 non-null object
brand                  50000 non-null object
notRepairedDamage      40171 non-null object
dateCreated            50000 non-null object
nrOfPictures           50000 non-null int64
postalCode             50000 non-null int64
lastSeen               50000 non-null object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

In [5]:
autos.columns

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

In [6]:
edits = {
    "dateCrawled":"date_crawled",
    "name":"name",
    "seller":"seller",
    "offerType":"offer_type",
    "price":"price",
    "abtest":"abtest",
    "vehicleType":"vehicle_type",
    "yearOfRegistration":"registration_year",
    "gearbox":"gearbox",
    "powerPS":"power_ps",
    "model":"model",
    "odometer":"odometer",
    "monthOfRegistration":"registration_month",
    "fuelType":"fuel_type",
    "brand":"brand",
    "notRepairedDamage":"unrepaired_damage",
    "dateCreated":"ad_created",
    "nrOfPictures":"nr_of_pictures",
    "postalCode":"postal_code",
    "lastSeen":"last_seen"}

autos.columns = autos.columns.to_series().map(edits)

In [7]:
autos.columns

Index(['date_crawled', 'name', 'seller', 'offer_type', 'price', 'abtest',
       'vehicle_type', 'registration_year', 'gearbox', 'power_ps', 'model',
       'odometer', 'registration_month', 'fuel_type', 'brand',
       'unrepaired_damage', 'ad_created', 'nr_of_pictures', 'postal_code',
       'last_seen'],
      dtype='object')

In [8]:
autos.head()

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

In [9]:
autos.describe()

,registration_year,power_ps,registration_month,nr_of_pictures,postal_code
count,50000.000000,50000.000000,50000.000000,50000.0,50000.000000
mean,2005.073280,116.355920,5.723360,0.0,50813.627300
std,105.712813,209.216627,3.711984,0.0,25779.747957
min,1000.000000,0.000000,0.000000,0.0,1067.000000
25%,1999.000000,70.000000,3.000000,0.0,30451.000000
50%,2003.000000,105.000000,6.000000,0.0,49577.000000
75%,2008.000000,150.000000,9.000000,0.0,71540.000000
max,9999.000000,17700.000000,12.000000,0.0,99998.000000

In [10]:
autos.price = autos.price.str.replace("$", "").str.replace(",", "").astype(int)

In [11]:
autos.odometer = autos.odometer.str.replace("km", "").str.replace(",", "").astype(int)
autos.rename({"odometer":"odometer_km"}, axis=1, inplace=True)

In [12]:
autos.odometer_km.describe()

count     50000.000000
mean     125732.700000
std       40042.211706
min        5000.000000
25%      125000.000000
50%      150000.000000
75%      150000.000000
max      150000.000000
Name: odometer_km, dtype: float64

In [13]:
autos.price.describe()

count    5.000000e+04
mean     9.840044e+03
std      4.811044e+05
min      0.000000e+00
25%      1.100000e+03
50%      2.950000e+03
75%      7.200000e+03
max      1.000000e+08
Name: price, dtype: float64

In [14]:
autos.odometer_km.unique().shape

(13,)

In [15]:
autos.price.unique().shape

(2357,)

In [16]:
autos.odometer_km.value_counts().sort_index(ascending=True)

5000        967
10000       264
20000       784
30000       789
40000       819
50000      1027
60000      1164
70000      1230
80000      1436
90000      1757
100000     2169
125000     5170
150000    32424
Name: odometer_km, dtype: int64

In [17]:
autos.price.value_counts().head()

0       1421
500      781
1500     734
2500     643
1000     639
Name: price, dtype: int64

In [18]:
autos.date_crawled.value_counts(normalize=True, dropna=False).sort_index(ascending=False)

2016-04-07 14:36:56    0.00002
2016-04-07 14:36:55    0.00002
2016-04-07 14:36:44    0.00002
2016-04-07 14:30:26    0.00002
2016-04-07 14:30:09    0.00002
2016-04-07 14:07:04    0.00002
2016-04-07 13:36:38    0.00002
2016-04-07 13:36:37    0.00002
2016-04-07 13:36:20    0.00002
2016-04-07 13:36:19    0.00002
2016-04-07 13:25:39    0.00002
2016-04-07 13:06:18    0.00002
2016-04-07 12:25:35    0.00002
2016-04-07 12:25:34    0.00002
2016-04-07 12:06:23    0.00002
2016-04-07 12:06:19    0.00002
2016-04-07 11:36:35    0.00002
2016-04-07 11:36:34    0.00004
2016-04-07 11:36:25    0.00002
2016-04-07 11:36:24    0.00002
2016-04-07 11:36:23    0.00002
2016-04-07 11:36:19    0.00002
2016-04-07 11:06:33    0.00002
2016-04-07 10:36:37    0.00004
2016-04-07 10:36:36    0.00002
2016-04-07 10:36:35    0.00002
2016-04-07 10:36:25    0.00002
2016-04-07 10:36:24    0.00002
2016-04-07 10:36:21    0.00002
2016-04-07 10:36:19    0.00002
                        ...
2016-03-05 14:11:40    0.00002
2016-03-05 14:11:25    0.00002
2016-03-05 14:11:15    0.00002
2016-03-05 14:11:14    0.00002
2016-03-05 14:11:05    0.00002
2016-03-05 14:11:03    0.00002
2016-03-05 14:10:46    0.00002
2016-03-05 14:10:20    0.00002
2016-03-05 14:10:18    0.00002
2016-03-05 14:09:58    0.00004
2016-03-05 14:09:57    0.00002
2016-03-05 14:09:56    0.00002
2016-03-05 14:09:46    0.00002
2016-03-05 14:09:38    0.00002
2016-03-05 14:09:22    0.00002
2016-03-05 14:09:20    0.00002
2016-03-05 14:09:05    0.00002
2016-03-05 14:09:02    0.00004
2016-03-05 14:08:42    0.00002
2016-03-05 14:08:27    0.00002
2016-03-05 14:08:05    0.00004
2016-03-05 14:08:00    0.00004
2016-03-05 14:07:45    0.00002
2016-03-05 14:07:40    0.00002
2016-03-05 14:07:26    0.00002
2016-03-05 14:07:21    0.00002
2016-03-05 14:07:08    0.00002
2016-03-05 14:07:04    0.00002
2016-03-05 14:06:40    0.00002
2016-03-05 14:06:30    0.00002
Name: date_crawled, Length: 48213, dtype: float64

In [19]:
autos.ad_created.value_counts(normalize=True, dropna=False).sort_index(ascending=True)

2015-06-11 00:00:00    0.00002
2015-08-10 00:00:00    0.00002
2015-09-09 00:00:00    0.00002
2015-11-10 00:00:00    0.00002
2015-12-05 00:00:00    0.00002
2015-12-30 00:00:00    0.00002
2016-01-03 00:00:00    0.00002
2016-01-07 00:00:00    0.00002
2016-01-10 00:00:00    0.00004
2016-01-13 00:00:00    0.00002
2016-01-14 00:00:00    0.00002
2016-01-16 00:00:00    0.00002
2016-01-22 00:00:00    0.00002
2016-01-27 00:00:00    0.00006
2016-01-29 00:00:00    0.00002
2016-02-01 00:00:00    0.00002
2016-02-02 00:00:00    0.00004
2016-02-05 00:00:00    0.00004
2016-02-07 00:00:00    0.00002
2016-02-08 00:00:00    0.00002
2016-02-09 00:00:00    0.00004
2016-02-11 00:00:00    0.00002
2016-02-12 00:00:00    0.00006
2016-02-14 00:00:00    0.00004
2016-02-16 00:00:00    0.00002
2016-02-17 00:00:00    0.00002
2016-02-18 00:00:00    0.00004
2016-02-19 00:00:00    0.00006
2016-02-20 00:00:00    0.00004
2016-02-21 00:00:00    0.00006
                        ...
2016-03-09 00:00:00    0.03324
2016-03-10 00:00:00    0.03186
2016-03-11 00:00:00    0.03278
2016-03-12 00:00:00    0.03662
2016-03-13 00:00:00    0.01692
2016-03-14 00:00:00    0.03522
2016-03-15 00:00:00    0.03374
2016-03-16 00:00:00    0.03000
2016-03-17 00:00:00    0.03120
2016-03-18 00:00:00    0.01372
2016-03-19 00:00:00    0.03384
2016-03-20 00:00:00    0.03786
2016-03-21 00:00:00    0.03772
2016-03-22 00:00:00    0.03280
2016-03-23 00:00:00    0.03218
2016-03-24 00:00:00    0.02908
2016-03-25 00:00:00    0.03188
2016-03-26 00:00:00    0.03256
2016-03-27 00:00:00    0.03090
2016-03-28 00:00:00    0.03496
2016-03-29 00:00:00    0.03414
2016-03-30 00:00:00    0.03344
2016-03-31 00:00:00    0.03192
2016-04-01 00:00:00    0.03380
2016-04-02 00:00:00    0.03508
2016-04-03 00:00:00    0.03892
2016-04-04 00:00:00    0.03688
2016-04-05 00:00:00    0.01184
2016-04-06 00:00:00    0.00326
2016-04-07 00:00:00    0.00128
Name: ad_created, Length: 76, dtype: float64

In [20]:
autos.last_seen.value_counts(normalize=True, dropna=False).sort_index(ascending=False)

2016-04-07 14:58:50    0.00008
2016-04-07 14:58:48    0.00006
2016-04-07 14:58:46    0.00002
2016-04-07 14:58:45    0.00002
2016-04-07 14:58:44    0.00006
2016-04-07 14:58:42    0.00004
2016-04-07 14:58:41    0.00002
2016-04-07 14:58:40    0.00002
2016-04-07 14:58:38    0.00002
2016-04-07 14:58:37    0.00002
2016-04-07 14:58:36    0.00006
2016-04-07 14:58:34    0.00004
2016-04-07 14:58:33    0.00004
2016-04-07 14:58:31    0.00004
2016-04-07 14:58:29    0.00006
2016-04-07 14:58:28    0.00004
2016-04-07 14:58:27    0.00004
2016-04-07 14:58:26    0.00004
2016-04-07 14:58:25    0.00002
2016-04-07 14:58:24    0.00004
2016-04-07 14:58:22    0.00002
2016-04-07 14:58:21    0.00006
2016-04-07 14:58:20    0.00002
2016-04-07 14:58:18    0.00010
2016-04-07 14:58:17    0.00006
2016-04-07 14:58:14    0.00002
2016-04-07 14:58:13    0.00002
2016-04-07 14:58:12    0.00004
2016-04-07 14:58:10    0.00004
2016-04-07 14:58:09    0.00004
                        ...
2016-03-05 19:17:17    0.00002
2016-03-05 19:16:36    0.00002
2016-03-05 19:15:42    0.00002
2016-03-05 19:15:20    0.00002
2016-03-05 19:15:08    0.00002
2016-03-05 18:50:38    0.00002
2016-03-05 18:47:14    0.00002
2016-03-05 18:17:58    0.00002
2016-03-05 17:46:01    0.00002
2016-03-05 17:44:54    0.00002
2016-03-05 17:44:50    0.00002
2016-03-05 17:40:14    0.00002
2016-03-05 17:39:19    0.00002
2016-03-05 17:17:02    0.00002
2016-03-05 17:16:23    0.00002
2016-03-05 17:16:14    0.00002
2016-03-05 17:16:12    0.00002
2016-03-05 17:15:45    0.00002
2016-03-05 16:47:28    0.00002
2016-03-05 16:45:57    0.00002
2016-03-05 15:47:44    0.00002
2016-03-05 15:47:38    0.00002
2016-03-05 15:45:43    0.00002
2016-03-05 15:41:30    0.00002
2016-03-05 15:28:10    0.00002
2016-03-05 15:16:47    0.00002
2016-03-05 15:16:11    0.00002
2016-03-05 14:49:34    0.00002
2016-03-05 14:46:02    0.00002
2016-03-05 14:45:46    0.00002
Name: last_seen, Length: 39481, dtype: float64

In [21]:
autos.registration_year.describe()

count    50000.000000
mean      2005.073280
std        105.712813
min       1000.000000
25%       1999.000000
50%       2003.000000
75%       2008.000000
max       9999.000000
Name: registration_year, dtype: float64

Cars can be registered between 1900 and 2016. Other must be removed.

In [22]:
autos = autos.drop(autos[~autos["registration_year"].between(1900, 2016)].index, axis=0)

In [23]:
autos.registration_year.value_counts(normalize=True)

2000    0.069834
2005    0.062776
1999    0.062464
2004    0.056988
2003    0.056779
2006    0.056384
2001    0.056280
2002    0.052740
1998    0.051074
2007    0.047972
2008    0.046452
2009    0.043683
1997    0.042225
2011    0.034022
2010    0.033251
1996    0.030066
2012    0.027546
2016    0.027401
1995    0.027338
2013    0.016782
2014    0.013867
1994    0.013742
1993    0.009265
2015    0.008308
1990    0.008224
1992    0.008141
1991    0.007412
1989    0.003769
1988    0.002957
1985    0.002186
          ...
1966    0.000458
1977    0.000458
1975    0.000396
1969    0.000396
1965    0.000354
1964    0.000250
1910    0.000187
1963    0.000187
1959    0.000146
1961    0.000125
1956    0.000104
1958    0.000083
1937    0.000083
1962    0.000083
1950    0.000062
1954    0.000042
1941    0.000042
1934    0.000042
1957    0.000042
1951    0.000042
1955    0.000042
1931    0.000021
1953    0.000021
1943    0.000021
1938    0.000021
1939    0.000021
1927    0.000021
1929    0.000021
1948    0.000021
1952    0.000021
Name: registration_year, Length: 78, dtype: float64

First 20 brands

In [24]:
autos.brand.value_counts()[:20]

volkswagen        10188
bmw                5284
opel               5195
mercedes_benz      4580
audi               4149
ford               3352
renault            2274
peugeot            1418
fiat               1242
seat                873
skoda               770
mazda               727
nissan              725
citroen             669
smart               668
toyota              599
sonstige_autos      526
hyundai             473
volvo               444
mini                415
Name: brand, dtype: int64

Brands with percentage of appearance in list is over 5%

In [25]:
auto = autos.brand.value_counts(normalize=True) > 0.05
selectedBrands = auto[auto==True].index
selectedBrands

Index(['volkswagen', 'bmw', 'opel', 'mercedes_benz', 'audi', 'ford'], dtype='object')

In [26]:
autos

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,5000,control,bus,2004,manuell,158,andere,150000,3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,8500,control,limousine,1997,automatik,286,7er,150000,6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,8990,test,limousine,2009,manuell,102,golf,70000,7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,4350,control,kleinwagen,2007,automatik,71,fortwo,70000,6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,1350,test,kombi,2003,manuell,0,focus,150000,7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,7900,test,bus,2006,automatik,150,voyager,150000,4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,300,test,limousine,1995,manuell,90,golf,150000,8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,1990,control,limousine,1998,manuell,90,golf,150000,12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,250,test,NaN,2000,manuell,0,arosa,150000,10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,590,control,bus,1997,manuell,90,megane,150000,7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,350,control,NaN,2000,NaN,0,NaN,150000,0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,5299,control,kleinwagen,2010,automatik,71,fortwo,50000,9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,1350,control,limousine,1999,manuell,101,a3,150000,11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,3999,test,kleinwagen,2007,manuell,75,clio,150000,9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,18900,test,coupe,1982,automatik,203,NaN,80000,6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,350,test,kombi,1999,manuell,101,vectra,150000,5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,5500,test,coupe,1990,manuell,205,scirocco,150000,6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,300,control,bus,1995,manuell,150,3er,150000,0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,4150,control,suv,2004,manuell,124,andere,150000,2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,3500,test,kombi,2003,manuell,131,a4,150000,5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,41500,test,cabrio,2004,manuell,320,911,150000,4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,25450,control,cabrio,2015,manuell,184,cooper,10000,1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,7999,control,bus,2010,manuell,120,NaN,150000,2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,48500,control,limousine,2014,automatik,306,5er,30000,12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,90,control,kombi,1996,manuell,116,NaN,150000,4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,777,control,kleinwagen,1992,manuell,54,polo,125000,2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,0,control,NaN,2005,NaN,0,NaN,150000,0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,5250,control,kleinwagen,2007,manuell,110,cooper,150000,7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,4999,test,kombi,2004,automatik,204,e_klasse,150000,10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
30,2016-03-14 11:47:31,Peugeot_206_Unfallfahrzeug,privat,Angebot,80,test,kleinwagen,2002,manuell,60,2_reihe,150000,6,benzin,peugeot,ja,2016-03-14 00:00:00,0,57076,2016-03-14 11:47:31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,15800,control,bus,2010,automatik,136,c4,60000,4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,950,test,kleinwagen,2001,manuell,50,lupo,150000,4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,3300,control,bus,2004,automatik,150,vito,150000,10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,6000,control,cabrio,2004,manuell,163,slk,150000,11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,0,control,cabrio,1983,manuell,70,golf,150000,2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,9700,control,kleinwagen,2012,automatik,88,jazz,100000,11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,5900,test,kombi,1992,automatik,150,80,150000,12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,5500,control,limousine,2003,manuell,116,c_klasse,150000,2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,900,control,limousine,1996,automatik,136,e_klasse,150000,9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,11000,test,kleinwagen,2011,manuell,90,polo,70000,11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,400,control,kombi,1995,manuell,105,escort,125000,3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,2000,control,kombi,1998,manuell,115,astra,150000,12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,1950,control,kleinwagen,2004,manuell,0,fabia,90000,7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,600,test,kleinwagen,1999,manuell,101,focus,150000,4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,0,test,NaN,2000,NaN,0,NaN,150000,0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,1000,control,NaN,1995,automatik,0,NaN,150000,0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,15900,control,limousine,2010,automatik,218,300c,125000,11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,21990,control,limousine,2013,manuell,150,a3,50000,11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,9550,control,coupe,2001,manuell,231,3er,150000,10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,150,test,kleinwagen,1997,manuell,0,polo,150000,5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,17500,test,limousine,2012,manuell,156,a_klasse,30000,12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,500,control,NaN,2016,manuell,0,twingo,150000,0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,4800,control,kleinwagen,2009,manuell,120,andere,125000,9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,1650,control,kleinwagen,1997,manuell,0,NaN,150000,7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,5000,control,kombi,2001,automatik,299,a6,150000,1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,24900,control,limousine,2011,automatik,239,q5,100000,1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,1980,control,cabrio,1996,manuell,75,astra,150000,5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,13200,test,cabrio,2014,automatik,69,500,5000,11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,22900,control,kombi,2013,manuell,150,a3,40000,11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,1250,control,limousine,1996,manuell,101,vectra,150000,1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

Mean price of cars created by brands defined above

In [27]:
brandPriceMean = {}
price = 0
for brand in selectedBrands:
    meanPrice = autos.loc[autos.brand == brand, "price"].mean()
    brandPriceMean[brand] = meanPrice
brandPriceMean

{'audi': 9093.65003615329,
 'bmw': 8334.645155185466,
 'ford': 7263.015811455847,
 'mercedes_benz': 30317.447816593885,
 'opel': 5252.61655437921,
 'volkswagen': 6516.457597173145}

In [28]:
brandMileageMean = {}
for brand in selectedBrands:
    meanMileage = autos.loc[autos.brand == brand, "odometer_km"].mean()
    brandMileageMean[brand] = meanMileage
brandMileageMean

{'audi': 129287.78018799711,
 'bmw': 132434.70855412565,
 'ford': 124046.83770883054,
 'mercedes_benz': 130860.26200873363,
 'opel': 129227.14148219442,
 'volkswagen': 128730.36906164115}

In [29]:
bpmSeries = pd.Series(brandPriceMean)
bmmSeries = pd.Series(brandMileageMean)

In [30]:
bpmDataframe = pd.DataFrame(bpmSeries, columns=["meanPrice"])

In [31]:
bpmDataframe["meanMileage"] = bmmSeries

In [32]:
bpmDataframe

                  meanPrice    meanMileage
audi            9093.650036  129287.780188
bmw             8334.645155  132434.708554
ford            7263.015811  124046.837709
mercedes_benz  30317.447817  130860.262009
opel            5252.616554  129227.141482
volkswagen      6516.457597  128730.369062

In [33]:
autos

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,5000,control,bus,2004,manuell,158,andere,150000,3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,8500,control,limousine,1997,automatik,286,7er,150000,6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,8990,test,limousine,2009,manuell,102,golf,70000,7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,4350,control,kleinwagen,2007,automatik,71,fortwo,70000,6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,1350,test,kombi,2003,manuell,0,focus,150000,7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,7900,test,bus,2006,automatik,150,voyager,150000,4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,300,test,limousine,1995,manuell,90,golf,150000,8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,1990,control,limousine,1998,manuell,90,golf,150000,12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,250,test,NaN,2000,manuell,0,arosa,150000,10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,590,control,bus,1997,manuell,90,megane,150000,7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,350,control,NaN,2000,NaN,0,NaN,150000,0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,5299,control,kleinwagen,2010,automatik,71,fortwo,50000,9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,1350,control,limousine,1999,manuell,101,a3,150000,11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,3999,test,kleinwagen,2007,manuell,75,clio,150000,9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,18900,test,coupe,1982,automatik,203,NaN,80000,6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,350,test,kombi,1999,manuell,101,vectra,150000,5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,5500,test,coupe,1990,manuell,205,scirocco,150000,6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,300,control,bus,1995,manuell,150,3er,150000,0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,4150,control,suv,2004,manuell,124,andere,150000,2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,3500,test,kombi,2003,manuell,131,a4,150000,5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,41500,test,cabrio,2004,manuell,320,911,150000,4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,25450,control,cabrio,2015,manuell,184,cooper,10000,1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,7999,control,bus,2010,manuell,120,NaN,150000,2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,48500,control,limousine,2014,automatik,306,5er,30000,12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,90,control,kombi,1996,manuell,116,NaN,150000,4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,777,control,kleinwagen,1992,manuell,54,polo,125000,2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,0,control,NaN,2005,NaN,0,NaN,150000,0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,5250,control,kleinwagen,2007,manuell,110,cooper,150000,7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,4999,test,kombi,2004,automatik,204,e_klasse,150000,10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
30,2016-03-14 11:47:31,Peugeot_206_Unfallfahrzeug,privat,Angebot,80,test,kleinwagen,2002,manuell,60,2_reihe,150000,6,benzin,peugeot,ja,2016-03-14 00:00:00,0,57076,2016-03-14 11:47:31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,15800,control,bus,2010,automatik,136,c4,60000,4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,950,test,kleinwagen,2001,manuell,50,lupo,150000,4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,3300,control,bus,2004,automatik,150,vito,150000,10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,6000,control,cabrio,2004,manuell,163,slk,150000,11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,0,control,cabrio,1983,manuell,70,golf,150000,2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,9700,control,kleinwagen,2012,automatik,88,jazz,100000,11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,5900,test,kombi,1992,automatik,150,80,150000,12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,5500,control,limousine,2003,manuell,116,c_klasse,150000,2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,900,control,limousine,1996,automatik,136,e_klasse,150000,9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,11000,test,kleinwagen,2011,manuell,90,polo,70000,11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,400,control,kombi,1995,manuell,105,escort,125000,3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,2000,control,kombi,1998,manuell,115,astra,150000,12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,1950,control,kleinwagen,2004,manuell,0,fabia,90000,7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,600,test,kleinwagen,1999,manuell,101,focus,150000,4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,0,test,NaN,2000,NaN,0,NaN,150000,0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,1000,control,NaN,1995,automatik,0,NaN,150000,0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,15900,control,limousine,2010,automatik,218,300c,125000,11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,21990,control,limousine,2013,manuell,150,a3,50000,11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,9550,control,coupe,2001,manuell,231,3er,150000,10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,150,test,kleinwagen,1997,manuell,0,polo,150000,5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,17500,test,limousine,2012,manuell,156,a_klasse,30000,12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,500,control,NaN,2016,manuell,0,twingo,150000,0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,4800,control,kleinwagen,2009,manuell,120,andere,125000,9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,1650,control,kleinwagen,1997,manuell,0,NaN,150000,7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,5000,control,kombi,2001,automatik,299,a6,150000,1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,24900,control,limousine,2011,automatik,239,q5,100000,1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,1980,control,cabrio,1996,manuell,75,astra,150000,5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,13200,test,cabrio,2014,automatik,69,500,5000,11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,22900,control,kombi,2013,manuell,150,a3,40000,11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,1250,control,limousine,1996,manuell,101,vectra,150000,1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

Identifying german words and translate it to english

In [34]:
autos.seller.unique()

array(['privat', 'gewerblich'], dtype=object)

In [35]:
translation = {"privat": "private", 
               "gewerblich": "commercial"}
autos.seller = autos.seller.map(translation)

In [36]:
autos.offer_type.unique()

array(['Angebot', 'Gesuch'], dtype=object)

In [37]:
translation = {"Angebot": "Offer", 
               "Gesuch": "Request"}
autos.offer_type = autos.offer_type.map(translation)

In [38]:
autos.vehicle_type.unique()

array(['bus', 'limousine', 'kleinwagen', 'kombi', nan, 'coupe', 'suv',
       'cabrio', 'andere'], dtype=object)

In [39]:
translation = {"bus": "bus", 
               "limousine": "limousine", 
               "kleinwagen": "small car",
               "kombi": "combi",
               "coupe": "coupe",
               "suv": "bus",
               "cabrio": "cabriolet",
               "andere": "v"}
autos.vehicle_type = autos.vehicle_type.map(translation)

In [40]:
autos.gearbox.unique()

array(['manuell', 'automatik', nan], dtype=object)

In [41]:
translation = {"manuell": "manually", 
               "automatik": "automatic"}
autos.gearbox = autos.gearbox.map(translation)

In [42]:
autos.fuel_type.unique()

array(['lpg', 'benzin', 'diesel', nan, 'cng', 'hybrid', 'elektro',
       'andere'], dtype=object)

In [43]:
translation = {"lpg": "lpg", 
               "benzin": "petrol",
               "diesel": "diesel", 
               "cng": "cng", 
               "hybrid": "hybrid", 
               "elektro": "electro", 
               "andere": "other", }
autos.fuel_type = autos.fuel_type.map(translation)

In [44]:
autos.unrepaired_damage.unique()

array(['nein', nan, 'ja'], dtype=object)

In [45]:
translation = {"nein": "no", 
               "ja": "yes"}
autos.unrepaired_damage = autos.unrepaired_damage.map(translation)

In [46]:
autos

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,private,Offer,5000,control,bus,2004,manually,158,andere,150000,3,lpg,peugeot,no,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,private,Offer,8500,control,limousine,1997,automatic,286,7er,150000,6,petrol,bmw,no,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,private,Offer,8990,test,limousine,2009,manually,102,golf,70000,7,petrol,volkswagen,no,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,private,Offer,4350,control,small car,2007,automatic,71,fortwo,70000,6,petrol,smart,no,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,private,Offer,1350,test,combi,2003,manually,0,focus,150000,7,petrol,ford,no,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,private,Offer,7900,test,bus,2006,automatic,150,voyager,150000,4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,private,Offer,300,test,limousine,1995,manually,90,golf,150000,8,petrol,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,private,Offer,1990,control,limousine,1998,manually,90,golf,150000,12,diesel,volkswagen,no,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,private,Offer,250,test,NaN,2000,manually,0,arosa,150000,10,NaN,seat,no,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,private,Offer,590,control,bus,1997,manually,90,megane,150000,7,petrol,renault,no,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,private,Offer,350,control,NaN,2000,NaN,0,NaN,150000,0,petrol,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,private,Offer,5299,control,small car,2010,automatic,71,fortwo,50000,9,petrol,smart,no,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,private,Offer,1350,control,limousine,1999,manually,101,a3,150000,11,petrol,audi,no,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,private,Offer,3999,test,small car,2007,manually,75,clio,150000,9,petrol,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,private,Offer,18900,test,coupe,1982,automatic,203,NaN,80000,6,petrol,sonstige_autos,no,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,private,Offer,350,test,combi,1999,manually,101,vectra,150000,5,petrol,opel,no,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,private,Offer,5500,test,coupe,1990,manually,205,scirocco,150000,6,petrol,volkswagen,no,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,private,Offer,300,control,bus,1995,manually,150,3er,150000,0,petrol,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,private,Offer,4150,control,bus,2004,manually,124,andere,150000,2,lpg,mazda,no,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,private,Offer,3500,test,combi,2003,manually,131,a4,150000,5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,private,Offer,41500,test,cabriolet,2004,manually,320,911,150000,4,petrol,porsche,no,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,private,Offer,25450,control,cabriolet,2015,manually,184,cooper,10000,1,petrol,mini,no,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,private,Offer,7999,control,bus,2010,manually,120,NaN,150000,2,diesel,peugeot,no,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,private,Offer,48500,control,limousine,2014,automatic,306,5er,30000,12,petrol,bmw,no,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,private,Offer,90,control,combi,1996,manually,116,NaN,150000,4,petrol,ford,yes,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,private,Offer,777,control,small car,1992,manually,54,polo,125000,2,petrol,volkswagen,no,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,private,Offer,0,control,NaN,2005,NaN,0,NaN,150000,0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,private,Offer,5250,control,small car,2007,manually,110,cooper,150000,7,diesel,mini,yes,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,private,Offer,4999,test,combi,2004,automatic,204,e_klasse,150000,10,diesel,mercedes_benz,no,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
30,2016-03-14 11:47:31,Peugeot_206_Unfallfahrzeug,private,Offer,80,test,small car,2002,manually,60,2_reihe,150000,6,petrol,peugeot,yes,2016-03-14 00:00:00,0,57076,2016-03-14 11:47:31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,private,Offer,15800,control,bus,2010,automatic,136,c4,60000,4,diesel,citroen,no,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,private,Offer,950,test,small car,2001,manually,50,lupo,150000,4,petrol,volkswagen,no,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,private,Offer,3300,control,bus,2004,automatic,150,vito,150000,10,diesel,mercedes_benz,yes,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,private,Offer,6000,control,cabriolet,2004,manually,163,slk,150000,11,petrol,mercedes_benz,no,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,private,Offer,0,control,cabriolet,1983,manually,70,golf,150000,2,petrol,volkswagen,no,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,private,Offer,9700,control,small car,2012,automatic,88,jazz,100000,11,hybrid,honda,no,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,private,Offer,5900,test,combi,1992,automatic,150,80,150000,12,petrol,audi,no,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,private,Offer,5500,control,limousine,2003,manually,116,c_klasse,150000,2,diesel,mercedes_benz,no,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,private,Offer,900,control,limousine,1996,automatic,136,e_klasse,150000,9,petrol,mercedes_benz,yes,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,private,Offer,11000,test,small car,2011,manually,90,polo,70000,11,diesel,volkswagen,no,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,private,Offer,400,control,combi,1995,manually,105,escort,125000,3,petrol,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,private,Offer,2000,control,combi,1998,manually,115,astra,150000,12,petrol,opel,no,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,private,Offer,1950,control,small car,2004,manually,0,fabia,90000,7,petrol,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,private,Offer,600,test,small car,1999,manually,101,focus,150000,4,petrol,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,private,Offer,0,test,NaN,2000,NaN,0,NaN,150000,0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,private,Offer,1000,control,NaN,1995,automatic,0,NaN,150000,0,petrol,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,private,Offer,15900,control,limousine,2010,automatic,218,300c,125000,11,diesel,chrysler,no,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,private,Offer,21990,control,limousine,2013,manually,150,a3,50000,11,diesel,audi,no,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,private,Offer,9550,control,coupe,2001,manually,231,3er,150000,10,petrol,bmw,no,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,private,Offer,150,test,small car,1997,manually,0,polo,150000,5,petrol,volkswagen,yes,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,private,Offer,17500,test,limousine,2012,manually,156,a_klasse,30000,12,petrol,mercedes_benz,no,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,private,Offer,500,control,NaN,2016,manually,0,twingo,150000,0,petrol,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,private,Offer,4800,control,small car,2009,manually,120,andere,125000,9,lpg,fiat,no,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,private,Offer,1650,control,small car,1997,manually,0,NaN,150000,7,petrol,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,private,Offer,5000,control,combi,2001,automatic,299,a6,150000,1,petrol,audi,no,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,private,Offer,24900,control,limousine,2011,automatic,239,q5,100000,1,diesel,audi,no,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,private,Offer,1980,control,cabriolet,1996,manually,75,astra,150000,5,petrol,opel,no,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,private,Offer,13200,test,cabriolet,2014,automatic,69,500,5000,11,petrol,fiat,no,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,private,Offer,22900,control,combi,2013,manually,150,a3,40000,11,diesel,audi,no,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,private,Offer,1250,control,limousine,1996,manually,101,vectra,150000,1,petrol,opel,no,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

Converting date to uniform numeric data

In [47]:
autos.date_crawled = pd.to_datetime(autos.date_crawled.str[:10]).dt.strftime("%Y%m%d").astype(int)
autos.ad_created = pd.to_datetime(autos.ad_created.str[:10]).dt.strftime("%Y%m%d").astype(int)
autos.last_seen = pd.to_datetime(autos.last_seen.str[:10]).dt.strftime("%Y%m%d").astype(int)

Most common brand/model combinations

In [56]:
for brand in autos.brand.value_counts().index:
    models = autos.loc[autos.brand == brand, "model"].value_counts(ascending=False).index
    print(brand, models[0] if len(models) > 0 else "None model is presented in data for this brand")

volkswagen golf
bmw 3er
opel corsa
mercedes_benz c_klasse
audi a4
ford focus
renault twingo
peugeot 2_reihe
fiat punto
seat ibiza
skoda octavia
mazda 3_reihe
nissan micra
citroen andere
smart fortwo
toyota yaris
sonstige_autos None model is presented in data for this brand
hyundai i_reihe
volvo v70
mini cooper
mitsubishi colt
honda civic
kia andere
alfa_romeo 156
porsche 911
suzuki andere
chevrolet andere
chrysler andere
daihatsu cuore
dacia sandero
jeep grand
subaru legacy
land_rover freelander
saab andere
jaguar andere
trabant 601
daewoo matiz
rover andere
lancia ypsilon
lada niva

In [61]:
autos.groupby(["odometer_km"]).mean()

,date_crawled,price,registration_year,power_ps,registration_month,ad_created,nr_of_pictures,postal_code,last_seen
odometer_km,,,,,,,,,
5000,2.016033e+07,11916.256861,1999.422613,83.328211,3.702525,2.016033e+07,0.0,46989.423710,2.016037e+07
10000,2.016033e+07,19890.598394,2008.325301,122.987952,5.859438,2.016033e+07,0.0,53510.718876,2.016038e+07
20000,2.016033e+07,17940.720839,2008.782438,149.401048,5.758847,2.016032e+07,0.0,53812.609436,2.016038e+07
30000,2.016033e+07,16414.455137,2009.283485,129.981795,6.059818,2.016033e+07,0.0,52044.495449,2.016038e+07
40000,2.016033e+07,49532.307116,2009.298377,127.429463,5.880150,2.016033e+07,0.0,52263.622971,2.016038e+07
50000,2.016033e+07,25919.245040,2008.075397,127.348214,6.046627,2.016032e+07,0.0,53672.392857,2.016038e+07
60000,2.016033e+07,12286.970097,2006.846966,125.507476,6.157432,2.016033e+07,0.0,51378.664028,2.016038e+07
70000,2.016033e+07,10817.819850,2006.152627,131.596330,6.157631,2.016033e+07,0.0,53737.064220,2.016038e+07
80000,2.016033e+07,9575.700573,2005.845272,129.572350,6.163324,2.016032e+07,0.0,51724.426218,2.016037e+07
90000,2.016033e+07,8350.228184,2004.791274,118.658019,5.929835,2.016033e+07,0.0,52040.780660,2.016037e+07
100000,2.016033e+07,12671.607109,2003.607583,116.492417,5.863033,2.016033e+07,0.0,52303.385308,2.016037e+07
125000,2.016033e+07,6286.593548,2003.767540,115.718548,5.945968,2.016033e+07,0.0,51855.611895,2.016037e+07
150000,2.016033e+07,7736.292823,2001.480067,115.033001,5.717716,2.016033e+07,0.0,50349.331529,2.016037e+07

In [79]:
priceComparisonOfDamagedCars = {}
unrepairedModels = autos.loc[autos.unrepaired_damage == "yes", "model"]
for model in unrepairedModels:
    unrepairedModelMeanPrice = autos.loc[(autos.unrepaired_damage == "yes") & (autos.model == model), "price"].mean()
    repairedModelMeanPrice = autos.loc[(autos.unrepaired_damage == "no") & (autos.model == model), "price"].mean()
    priceComparisonOfDamagedCars[model] = unrepairedModelMeanPrice, repairedModelMeanPrice
priceComparisonOfDamagedCars

{nan: (nan, nan),
 '911': (20833.333333333332, 73669.83846153846),
 'viano': (24333.333333333332, 20365.254545454547),
 'x_reihe': (11625.333333333334, 19202.803846153845),
 'outlander': (2850.0, 11293.470588235294),
 'c2': (1547.5714285714287, 3494.8947368421054),
 'escort': (265.7142857142857, 197308.9649122807),
 'ibiza': (1342.7837837837837, 4242.708171206225),
 'e_klasse': (4265.365853658536, 9162.488857938719),
 'picanto': (2670.0, 3586.128205128205),
 's60': (3500.0, 7379.142857142857),
 'terios': (1500.0, 4590.0),
 '5er': (3706.532710280374, 8790.01393728223),
 '100': (874.875, 2031.725),
 'legacy': (1440.0, 3232.9473684210525),
 's_klasse': (5552.727272727273, 15339.035714285714),
 '900': (383.3333333333333, 2542.7),
 's_type': (800.0, 6848.9),
 'zafira': (2091.0363636363636, 3942.464882943144),
 'kangoo': (1435.25, 3144.2698412698414),
 'antara': (3750.0, 9926.833333333334),
 'berlingo': (919.8, 4103.726027397261),
 'sirion': (490.0, 2024.75),
 'i3': (250.0, nan),
 'ducato': (3335.285714285714, 5219.642857142857),
 'c_reihe': (2999.0, 8339.076923076924),
 '5_reihe': (4366.666666666667, 8067.04347826087),
 'kaefer': (2960.0, 8916.645161290322),
 'vectra': (878.8658536585366, 38499.2294117647),
 'forester': (1700.0, 3152.222222222222),
 'mondeo': (1021.9651162790698, 3802.6485623003196),
 'c1': (1490.0, 4190.818181818182),
 'vito': (3658.0588235294117, 8369.5125),
 'galant': (1000.0, 1831.125),
 'a8': (3780.0, 11326.949152542373),
 'bora': (1762.4166666666667, 2408.3150684931506),
 'alhambra': (6233.333333333333, 6413.5),
 'sharan': (4580.8125, 6643.727272727273),
 'focus': (1582.0860215053763, 5841.520426287744),
 'lybra': (799.0, 659.8),
 'vivaro': (4879.666666666667, 8878.844444444445),
 'c_max': (2333.1666666666665, 7189.090909090909),
 'cuore': (631.25, 1393.6808510638298),
 'cooper': (4271.111111111111, 11967.05138339921),
 'q7': (11950.0, 22040.184210526317),
 'signum': (2642.1428571428573, 4880.046511627907),
 'almera': (949.8571428571429, 2005.1076923076923),
 'v50': (3495.0, 5323.56),
 'touran': (5172.882352941177, 8601.212827988338),
 'rio': (2583.1666666666665, 4153.84375),
 'lanos': (200.0, 593.625),
 '9000': (200.0, 2912.25),
 'panda': (1374.8333333333333, 3653.7258064516127),
 'matiz': (524.5, 1802.3333333333333),
 'transit': (1871.75, 5141.902777777777),
 'a5': (21649.8, 22454.473214285714),
 'note': (3875.0, 5588.368421052632),
 'grand': (3583.1111111111113, 10052.108108108108),
 'kalos': (850.0, 1508.25),
 'tucson': (3690.0, 6134.571428571428),
 'micra': (836.030303030303, 2545.682926829268),
 'scenic': (906.32, 2910.846153846154),
 'ptcruiser': (1699.6666666666667, 2472.5),
 'a6': (3135.701030927835, 9611.166394779772),
 'c3': (3500.0, 3991.9830508474574),
 'caddy': (4449.411764705882, 7898.617834394904),
 'sandero': (4219.25, 5666.333333333333),
 'freelander': (4016.6666666666665, 7012.68),
 'citigo': (3990.0, 7746.105263157895),
 '601': (556.2857142857143, 2914.75),
 'corolla': (1623.3333333333333, 2626.2615384615383),
 'mustang': (7733.333333333333, 22960.025),
 'up': (6449.333333333333, 8371.279069767443),
 'm_reihe': (8900.0, 27624.441860465115),
 'wrangler': (3450.0, 17559.75),
 'r19': (662.25, 759.8),
 'calibra': (1200.0, 2998.8333333333335),
 'x_type': (1424.75, 10132.0),
 'andere': (2333.4371859296484, 8318.373397435897),
 'stilo': (839.7333333333333, 1769.560975609756),
 'ceed': (3400.0, 9047.777777777777),
 'a_klasse': (1610.0727272727272, 4536.6560975609755),
 'fiesta': (1016.5897435897435, 3430.906432748538),
 'seicento': (357.0, 1035.4761904761904),
 'sorento': (3549.8, 9139.153846153846),
 'verso': (7347.5, 7539.121951219512),
 'accord': (2017.8, 5425.5),
 'v70': (1494.142857142857, 4852.71875),
 'octavia': (4606.5, 8339.256),
 'kadett': (1438.5714285714287, 4185.0),
 'lancer': (506.25, 6407.470588235294),
 'ypsilon': (97.5, 1450.5),
 'x_trail': (3400.0, 7894.387096774193),
 'getz': (948.625, 2154.121212121212),
 'aveo': (2957.5, 4993.266666666666),
 '159': (7800.0, 6659.653846153846),
 'a4': (2886.21359223301, 8019.117021276596),
 'impreza': (4991.666666666667, 8974.3125),
 'combo': (2082.1111111111113, 3355.025641025641),
 'primera': (999.6111111111111, 1603.7142857142858),
 'discovery': (1725.0, 15154.363636363636),
 '80': (580.3333333333334, 1698.881188118812),
 '7er': (5070.846153846154, 10081.882978723404),
 'polo': (934.4397905759163, 3164.7879890809827),
 'voyager': (1329.8, 1696.2),
 'sprinter': (5260.0, 6940.366666666667),
 'forfour': (1074.75, 2874.4117647058824),
 'g_klasse': (6375.0, 25956.736842105263),
 'cherokee': (533.3333333333334, 5966.636363636364),
 'astra': (1261.3108108108108, 3907.5377551020406),
 'one': (5566.666666666667, 7674.698795180723),
 'slk': (3641.6666666666665, 12632.704225352112),
 'altea': (3133.3333333333335, 6376.472222222223),
 'golf': (1736.9969418960245, 5996.137918352335),
 'justy': (322.5, 2574.1428571428573),
 'navara': (4000.0, 12663.777777777777),
 '3er': (2163.8478260869565, 6844.409698169223),
 'santa': (1999.75, 7835.272727272727),
 'leon': (3585.6428571428573, 8837.375796178343),
 'arosa': (543.6875, 1137.967741935484),
 'auris': (4749.5, 10198.407407407407),
 '1_reihe': (505.5, 1843.0740740740741),
 'lupo': (745.4883720930233, 1518.9345794392523),
 'c_klasse': (3739.635135135135, 7686.884742041712),
 'qashqai': (11783.333333333334, 13140.353846153846),
 'carisma': (651.6153846153846, 1184.6285714285714),
 'omega': (606.975, 1261.96875),
 '156': (973.9545454545455, 1689.5166666666667),
 'corsa': (1135.0344827586207, 2239.3092979127136),
 'logan': (1200.0, 3766.5555555555557),
 'a2': (2333.3333333333335, 3808.848484848485),
 'swift': (1046.0, 4290.782608695652),
 'beetle': (3094.0, 7479.148148148148),
 'colt': (1110.4705882352941, 2796.24),
 'fortwo': (1507.1025641025642, 4011.6495327102803),
 '850': (580.0, 2280.3888888888887),
 'fabia': (2199.0434782608695, 4584.642857142857),
 'toledo': (1089.8, 2084.703703703704),
 '300c': (0.0, 11998.9),
 '2_reihe': (1402.142857142857, 3459.4144736842104),
 'cayenne': (17666.666666666668, 25918.923076923078),
 'transporter': (4702.633333333333, 11813.458661417322),
 '1er': (6026.25, 11963.190265486726),
 'yaris': (3650.0, 4435.9655172413795),
 'bravo': (275.0, 2898.1724137931033),
 'aygo': (3112.5, 3589.586956521739),
 'rav': (6829.666666666667, 8930.78947368421),
 'tt': (7521.111111111111, 13629.462809917355),
 '4_reihe': (1190.8181818181818, 4765.592592592592),
 'ka': (476.9183673469388, 1787.8916256157636),
 'nubira': (574.5, 1362.25),
 'twingo': (741.1973684210526, 1726.847290640394),
 'cl': (14425.0, 12802.58064516129),
 '500': (3455.0, 8246.951923076924),
 'punto': (792.0714285714286, 1894.3110236220473),
 'rx_reihe': (2945.0, 8144.277777777777),
 'move': (400.0, 683.1666666666666),
 'eos': (7500.0, 11690.161290322581),
 'clio': (1036.3333333333333, 2774.4298507462686),
 'passat': (2039.3553719008264, 5686.190380761523),
 'agila': (829.875, 1703.0243902439024),
 'modus': (1950.0, 3233.24),
 'range_rover': (1800.0, 25411.428571428572),
 'jazz': (3012.5, 4851.5161290322585),
 'avensis': (2512.5, 5556.372881355932),
 'defender': (12245.0, 33009.125),
 'duster': (8500.0, 9350.04),
 'm_klasse': (5334.1, 14260.217741935483),
 '3_reihe': (1129.112676056338, 3593.58357771261),
 'megane': (1101.7142857142858, 4046.563559322034),
 'civic': (826.4117647058823, 3939.7391304347825),
 '6_reihe': (1161.857142857143, 4490.843478260869),
 'fusion': (1923.3333333333333, 3935.653846153846),
 'v_klasse': (3512.25, 15362.25),
 'roomster': (2799.5, 6767.193548387097),
 'carnival': (2008.3333333333333, 2178.9),
 'jetta': (999990.0, 5339.961538461538),
 'c4': (4171.0, 6810.765957446809),
 'superb': (10639.6, 9682.0),
 'kuga': (6390.0, 17622.052631578947),
 'samara': (300.0, 1499.0),
 'v40': (702.4285714285714, 2157.1428571428573),
 'espace': (583.5, 3433.769230769231),
 'jimny': (5555.333333333333, 6685.285714285715),
 'pajero': (2724.75, 9772.416666666666),
 'cordoba': (500.0, 921.1724137931035),
 'clk': (2981.5384615384614, 6739.855670103093),
 'tigra': (746.6, 3159.890625),
 'galaxy': (2484.9166666666665, 5136.930693069307),
 'sportage': (1200.0, 12591.702127659575),
 'mx_reihe': (2019.8, 6340.421052631579),
 'doblo': (1587.5, 3963.0882352941176),
 'xc_reihe': (11450.0, 13378.673913043478),
 'insignia': (4766.666666666667, 12293.88),
 'touareg': (20933.333333333332, 15977.154761904761),
 'niva': (2500.0, 3449.75),
 'a3': (2728.720588235294, 9176.349606299213),
 'fox': (1455.0, 2848.4626865671644),
 '147': (1286.8461538461538, 2722.8545454545456),
 'c5': (3072.1111111111113, 5300.964285714285),
 'meriva': (3256.076923076923, 4869.690265486725),
 'i_reihe': (5379.083333333333, 8354.802721088436),
 'sl': (6500.0, 24742.67816091954),
 'b_klasse': (4265.555555555556, 11266.61320754717),
 'cr_reihe': (2190.0, 6799.166666666667),
 'laguna': (1299.2142857142858, 2567.0087719298244)}

In [95]:
cheaper = {}
for key in priceComparisonOfDamagedCars:
    value = priceComparisonOfDamagedCars[key]
    cheaper[key] = value[1] - value[0]

cheaper

{nan: nan,
 'caddy': 3449.206069689022,
 'viano': -3968.078787878785,
 'x_reihe': 7577.470512820511,
 'outlander': 8443.470588235294,
 'c2': 1947.3233082706768,
 'escort': 197043.2506265664,
 'e_klasse': 4897.123004280183,
 'picanto': 916.1282051282051,
 '5er': 5083.4812270018565,
 'a8': 7546.949152542373,
 '100': 1156.85,
 'discovery': 13429.363636363636,
 's_klasse': 9786.308441558442,
 '900': 2159.3666666666663,
 'zafira': 1851.4285193067803,
 'kangoo': 1709.0198412698414,
 'modus': 1283.2399999999998,
 's60': 3879.142857142857,
 'ducato': 1884.3571428571427,
 'c_reihe': 5340.076923076924,
 '5_reihe': 3700.376811594203,
 'kaefer': 5956.645161290322,
 'vectra': 37620.36355810617,
 'forester': 1452.2222222222222,
 'c1': 2700.818181818182,
 'vito': 4711.453676470589,
 'galant': 831.125,
 'qashqai': 1357.0205128205125,
 'bora': 645.8984018264839,
 'alhambra': 180.16666666666697,
 'sharan': 2062.914772727273,
 'focus': 4259.434404782368,
 'lybra': -139.20000000000005,
 'vivaro': 3999.177777777778,
 'panda': 2278.8924731182797,
 'cuore': 762.4308510638298,
 'cooper': 7695.940272288099,
 'sprinter': 1680.3666666666668,
 'signum': 2237.90365448505,
 'almera': 1055.2505494505494,
 'v50': 1828.5600000000004,
 'touran': 3428.3304750471616,
 '500': 4791.951923076924,
 'lanos': 393.625,
 '9000': 2712.25,
 'c_max': 4855.924242424242,
 'matiz': 1277.8333333333333,
 'transit': 3270.1527777777774,
 'a5': 804.6732142857145,
 'note': 1713.3684210526317,
 'grand': 6468.996996996997,
 'kalos': 658.25,
 'tucson': 2444.5714285714284,
 'micra': 1709.6526237989651,
 'scenic': 2004.5261538461536,
 'ptcruiser': 772.8333333333333,
 'a6': 6475.465363851937,
 'c3': 491.98305084745743,
 '911': 52836.50512820513,
 'sandero': 1447.083333333333,
 'freelander': 2996.013333333334,
 'citigo': 3756.105263157895,
 'b_klasse': 7001.057651991615,
 'sportage': 11391.702127659575,
 '601': 2358.464285714286,
 'corolla': 1002.928205128205,
 'mustang': 15226.69166666667,
 'up': 1921.9457364341097,
 'm_reihe': 18724.441860465115,
 '1er': 5936.940265486726,
 'r19': 97.54999999999995,
 'astra': 2646.2269442912298,
 'calibra': 1798.8333333333335,
 'x_type': 8707.25,
 'andere': 5984.936211506249,
 'laguna': 1267.7944862155387,
 'stilo': 929.8276422764227,
 'toledo': 994.903703703704,
 'a_klasse': 2926.5833702882483,
 'fiesta': 2414.3166891587944,
 'seicento': 678.4761904761904,
 'sorento': 5589.353846153846,
 'verso': 191.62195121951208,
 'accord': 3407.7,
 'v70': 3358.575892857143,
 'clk': 3758.3172085646315,
 'kadett': 2746.4285714285716,
 'golf': 4259.14097645631,
 'primera': 604.1031746031747,
 'getz': 1205.496212121212,
 'aveo': 2035.7666666666664,
 '159': -1140.3461538461543,
 'a4': 5132.903429043586,
 'v_klasse': 11850.0,
 'impreza': 3982.645833333333,
 'combo': 1272.9145299145298,
 'rio': 1570.6770833333335,
 'legacy': 1792.9473684210525,
 '80': 1118.5478547854786,
 '7er': 5011.03682487725,
 'polo': 2230.3481985050666,
 'voyager': 366.4000000000001,
 'q7': 10090.184210526317,
 'forfour': 1799.6617647058824,
 'g_klasse': 19581.736842105263,
 'cherokee': 5433.303030303031,
 'i3': nan,
 'one': 2108.0321285140562,
 'slk': 8991.037558685446,
 'altea': 3243.138888888889,
 'lancer': 5901.220588235294,
 'justy': 2251.6428571428573,
 'navara': 8663.777777777777,
 '3er': 4680.561872082266,
 'santa': 5835.522727272727,
 'leon': 5251.732939035486,
 'arosa': 594.2802419354839,
 'touareg': -4956.178571428571,
 'auris': 5448.907407407407,
 '1_reihe': 1337.5740740740741,
 'lupo': 773.446207346229,
 'c_klasse': 3947.2496069065774,
 'carisma': 533.0131868131867,
 'omega': 654.99375,
 '156': 715.5621212121212,
 'roomster': 3967.6935483870966,
 'corsa': 1104.274815154093,
 'logan': 2566.5555555555557,
 'a2': 1475.5151515151515,
 'swift': 3244.782608695652,
 'beetle': 4385.148148148148,
 'colt': 1685.7694117647056,
 '850': 1700.3888888888887,
 'fabia': 2385.5993788819874,
 'mondeo': 2780.68344602125,
 '300c': 11998.9,
 '2_reihe': 2057.271616541353,
 'cayenne': 8252.25641025641,
 'sirion': 1534.75,
 'transporter': 7110.825328083989,
 'wrangler': 14109.75,
 'bravo': 2623.1724137931033,
 'aygo': 477.086956521739,
 'clio': 1738.0965174129353,
 'tt': 6108.351698806244,
 '4_reihe': 3574.77441077441,
 'ka': 1310.9732582688248,
 'nubira': 787.75,
 'twingo': 985.6499222193414,
 'cl': -1622.4193548387102,
 'punto': 1102.2395950506188,
 'rx_reihe': 5199.277777777777,
 'move': 283.16666666666663,
 'eos': 4190.161290322581,
 'rav': 2101.122807017543,
 'passat': 3646.8350088606962,
 'agila': 873.1493902439024,
 'berlingo': 3183.9260273972604,
 'range_rover': 23611.428571428572,
 'jazz': 1839.0161290322585,
 'avensis': 3043.872881355932,
 'defender': 20764.125,
 'duster': 850.0400000000009,
 'm_klasse': 8926.117741935483,
 'terios': 3090.0,
 'megane': 2944.8492736077483,
 'civic': 3113.3273657289,
 '6_reihe': 3328.986335403726,
 'fusion': 2012.320512820513,
 'ibiza': 2899.9243874224417,
 'ceed': 5647.777777777777,
 'carnival': 170.56666666666683,
 'jetta': -994650.0384615385,
 'c4': 2639.765957446809,
 'superb': -957.6000000000004,
 'kuga': 11232.052631578947,
 'samara': 1199.0,
 'yaris': 785.9655172413795,
 'espace': 2850.269230769231,
 'jimny': 1129.9523809523816,
 'cordoba': 421.1724137931035,
 'octavia': 3732.7559999999994,
 'tigra': 2413.290625,
 'galaxy': 2652.014026402641,
 'pajero': 7047.666666666666,
 'mx_reihe': 4320.621052631579,
 'doblo': 2375.5882352941176,
 'xc_reihe': 1928.673913043478,
 'insignia': 7527.213333333332,
 's_type': 6048.9,
 'v40': 1454.7142857142858,
 'niva': 949.75,
 'ypsilon': 1353.0,
 'a3': 6447.629018063919,
 'antara': 6176.833333333334,
 '147': 1436.0083916083918,
 'c5': 2228.853174603174,
 'meriva': 1613.6133424098025,
 '3_reihe': 2464.470901656272,
 'i_reihe': 2975.7193877551026,
 'sl': 18242.67816091954,
 'x_trail': 4494.387096774193,
 'cr_reihe': 4609.166666666667,
 'fox': 1393.4626865671644,
 'fortwo': 2504.546968607716}

In [62]:
autos

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,20160326,Peugeot_807_160_NAVTECH_ON_BOARD,private,Offer,5000,control,bus,2004,manually,158,andere,150000,3,lpg,peugeot,no,20160326,0,79588,20160406
1,20160404,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,private,Offer,8500,control,limousine,1997,automatic,286,7er,150000,6,petrol,bmw,no,20160404,0,71034,20160406
2,20160326,Volkswagen_Golf_1.6_United,private,Offer,8990,test,limousine,2009,manually,102,golf,70000,7,petrol,volkswagen,no,20160326,0,35394,20160406
3,20160312,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,private,Offer,4350,control,small car,2007,automatic,71,fortwo,70000,6,petrol,smart,no,20160312,0,33729,20160315
4,20160401,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,private,Offer,1350,test,combi,2003,manually,0,focus,150000,7,petrol,ford,no,20160401,0,39218,20160401
5,20160321,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,private,Offer,7900,test,bus,2006,automatic,150,voyager,150000,4,diesel,chrysler,NaN,20160321,0,22962,20160406
6,20160320,VW_Golf_III_GT_Special_Electronic_Green_Metall...,private,Offer,300,test,limousine,1995,manually,90,golf,150000,8,petrol,volkswagen,NaN,20160320,0,31535,20160323
7,20160316,Golf_IV_1.9_TDI_90PS,private,Offer,1990,control,limousine,1998,manually,90,golf,150000,12,diesel,volkswagen,no,20160316,0,53474,20160407
8,20160322,Seat_Arosa,private,Offer,250,test,NaN,2000,manually,0,arosa,150000,10,NaN,seat,no,20160322,0,7426,20160326
9,20160316,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,private,Offer,590,control,bus,1997,manually,90,megane,150000,7,petrol,renault,no,20160316,0,15749,20160406
11,20160316,Mercedes_A140_Motorschaden,private,Offer,350,control,NaN,2000,NaN,0,NaN,150000,0,petrol,mercedes_benz,NaN,20160316,0,17498,20160316
12,20160331,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,private,Offer,5299,control,small car,2010,automatic,71,fortwo,50000,9,petrol,smart,no,20160331,0,34590,20160406
13,20160323,Audi_A3_1.6_tuning,private,Offer,1350,control,limousine,1999,manually,101,a3,150000,11,petrol,audi,no,20160323,0,12043,20160401
14,20160323,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,private,Offer,3999,test,small car,2007,manually,75,clio,150000,9,petrol,renault,NaN,20160323,0,81737,20160401
15,20160401,Corvette_C3_Coupe_T_Top_Crossfire_Injection,private,Offer,18900,test,coupe,1982,automatic,203,NaN,80000,6,petrol,sonstige_autos,no,20160401,0,61276,20160402
16,20160316,Opel_Vectra_B_Kombi,private,Offer,350,test,combi,1999,manually,101,vectra,150000,5,petrol,opel,no,20160316,0,57299,20160318
17,20160329,Volkswagen_Scirocco_2_G60,private,Offer,5500,test,coupe,1990,manually,205,scirocco,150000,6,petrol,volkswagen,no,20160329,0,74821,20160405
18,20160326,Verkaufen_mein_bmw_e36_320_i_touring,private,Offer,300,control,bus,1995,manually,150,3er,150000,0,petrol,bmw,NaN,20160326,0,54329,20160402
19,20160317,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,private,Offer,4150,control,bus,2004,manually,124,andere,150000,2,lpg,mazda,no,20160317,0,40878,20160317
20,20160305,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,private,Offer,3500,test,combi,2003,manually,131,a4,150000,5,diesel,audi,NaN,20160305,0,53913,20160307
21,20160306,Porsche_911_Carrera_4S_Cabrio,private,Offer,41500,test,cabriolet,2004,manually,320,911,150000,4,petrol,porsche,no,20160306,0,65428,20160405
22,20160328,MINI_Cooper_S_Cabrio,private,Offer,25450,control,cabriolet,2015,manually,184,cooper,10000,1,petrol,mini,no,20160328,0,44789,20160401
23,20160310,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,private,Offer,7999,control,bus,2010,manually,120,NaN,150000,2,diesel,peugeot,no,20160310,0,30900,20160317
24,20160403,BMW_535i_xDrive_Sport_Aut.,private,Offer,48500,control,limousine,2014,automatic,306,5er,30000,12,petrol,bmw,no,20160403,0,22547,20160407
25,20160321,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,private,Offer,90,control,combi,1996,manually,116,NaN,150000,4,petrol,ford,yes,20160321,0,27574,20160401
26,20160403,Volkswagen_Polo_Fox,private,Offer,777,control,small car,1992,manually,54,polo,125000,2,petrol,volkswagen,no,20160403,0,38110,20160405
27,20160327,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,private,Offer,0,control,NaN,2005,NaN,0,NaN,150000,0,NaN,ford,NaN,20160327,0,66701,20160327
28,20160319,MINI_Cooper_D,private,Offer,5250,control,small car,2007,manually,110,cooper,150000,7,diesel,mini,yes,20160319,0,15745,20160407
29,20160402,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,private,Offer,4999,test,combi,2004,automatic,204,e_klasse,150000,10,diesel,mercedes_benz,no,20160402,0,47638,20160402
30,20160314,Peugeot_206_Unfallfahrzeug,private,Offer,80,test,small car,2002,manually,60,2_reihe,150000,6,petrol,peugeot,yes,20160314,0,57076,20160314
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,20160321,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,private,Offer,15800,control,bus,2010,automatic,136,c4,60000,4,diesel,citroen,no,20160321,0,14947,20160407
49971,20160329,W.Lupo_1.0,private,Offer,950,test,small car,2001,manually,50,lupo,150000,4,petrol,volkswagen,no,20160329,0,65197,20160329
49972,20160326,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,private,Offer,3300,control,bus,2004,automatic,150,vito,150000,10,diesel,mercedes_benz,yes,20160326,0,65326,20160328
49973,20160327,Mercedes_Benz_SLK_200_Kompressor,private,Offer,6000,control,cabriolet,2004,manually,163,slk,150000,11,petrol,mercedes_benz,no,20160327,0,53567,20160327
49974,20160320,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,private,Offer,0,control,cabriolet,1983,manually,70,golf,150000,2,petrol,volkswagen,no,20160320,0,8209,20160327
49975,20160327,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,private,Offer,9700,control,small car,2012,automatic,88,jazz,100000,11,hybrid,honda,no,20160327,0,84385,20160405
49976,20160319,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,private,Offer,5900,test,combi,1992,automatic,150,80,150000,12,petrol,audi,no,20160319,0,36100,20160407
49977,20160331,Mercedes_Benz_C200_Cdi_W203,private,Offer,5500,control,limousine,2003,manually,116,c_klasse,150000,2,diesel,mercedes_benz,no,20160331,0,33739,20160406
49978,20160404,Mercedes_Benz_E_200_Classic,private,Offer,900,control,limousine,1996,automatic,136,e_klasse,150000,9,petrol,mercedes_benz,yes,20160404,0,24405,20160406
49979,20160320,Volkswagen_Polo_1.6_TDI_Style,private,Offer,11000,test,small car,2011,manually,90,polo,70000,11,diesel,volkswagen,no,20160320,0,48455,20160407
49980,20160312,Ford_Escort_Turnier_16V,private,Offer,400,control,combi,1995,manually,105,escort,125000,3,petrol,ford,NaN,20160312,0,56218,20160406
49981,20160315,Opel_Astra_Kombi_mit_Anhaengerkupplung,private,Offer,2000,control,combi,1998,manually,115,astra,150000,12,petrol,opel,no,20160315,0,86859,20160405
49982,20160329,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,private,Offer,1950,control,small car,2004,manually,0,fabia,90000,7,petrol,skoda,NaN,20160329,0,45884,20160329
49983,20160306,Ford_focus_99,private,Offer,600,test,small car,1999,manually,101,focus,150000,4,petrol,ford,NaN,20160306,0,52477,20160309
49984,20160331,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,private,Offer,0,test,NaN,2000,NaN,0,NaN,150000,0,NaN,sonstige_autos,NaN,20160331,0,12103,20160402
49985,20160402,Verkaufe_meinen_vw_vento!,private,Offer,1000,control,NaN,1995,automatic,0,NaN,150000,0,petrol,volkswagen,NaN,20160402,0,30900,20160406
49986,20160404,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,private,Offer,15900,control,limousine,2010,automatic,218,300c,125000,11,diesel,chrysler,no,20160404,0,73527,20160406
49987,20160322,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,private,Offer,21990,control,limousine,2013,manually,150,a3,50000,11,diesel,audi,no,20160322,0,94362,20160326
49988,20160328,BMW_330_Ci,private,Offer,9550,control,coupe,2001,manually,231,3er,150000,10,petrol,bmw,no,20160328,0,83646,20160407
49989,20160311,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,private,Offer,150,test,small car,1997,manually,0,polo,150000,5,petrol,volkswagen,yes,20160311,0,21244,20160312
49990,20160321,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,private,Offer,17500,test,limousine,2012,manually,156,a_klasse,30000,12,petrol,mercedes_benz,no,20160321,0,58239,20160406
49991,20160306,Kleinwagen,private,Offer,500,control,NaN,2016,manually,0,twingo,150000,0,petrol,renault,NaN,20160306,0,61350,20160306
49992,20160310,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,private,Offer,4800,control,small car,2009,manually,120,andere,125000,9,lpg,fiat,no,20160310,0,68642,20160313
49993,20160315,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,private,Offer,1650,control,small car,1997,manually,0,NaN,150000,7,petrol,audi,NaN,20160315,0,65203,20160406
49994,20160322,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,private,Offer,5000,control,combi,2001,automatic,299,a6,150000,1,petrol,audi,no,20160322,0,46537,20160406
49995,20160327,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,private,Offer,24900,control,limousine,2011,automatic,239,q5,100000,1,diesel,audi,no,20160327,0,82131,20160401
49996,20160328,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,private,Offer,1980,control,cabriolet,1996,manually,75,astra,150000,5,petrol,opel,no,20160328,0,44807,20160402
49997,20160402,Fiat_500_C_1.2_Dualogic_Lounge,private,Offer,13200,test,cabriolet,2014,automatic,69,500,5000,11,petrol,fiat,no,20160402,0,73430,20160404
49998,20160308,Audi_A3_2.0_TDI_Sportback_Ambition,private,Offer,22900,control,combi,2013,manually,150,a3,40000,11,diesel,audi,no,20160308,0,35683,20160405
49999,20160314,Opel_Vectra_1.6_16V,private,Offer,1250,control,limousine,1996,manually,101,vectra,150000,1,petrol,opel,no,20160313,0,45897,20160406